/**
 * Framework-free song model. Angular, the engines, and the file writers
 * all import this barrel and nothing underneath it.
 */
export {
  LEGACY_PROJECT_VERSION,
  PATTERN_ROWS,
  PROJECT_VERSION,
  EFFECT_CMDS,
  formatEffect,
  type Cell,
  type CellEffect,
  type ChipId,
  type ColumnId,
  type Cursor,
  type EffectCmd,
  type Instrument,
  type InstrumentKind,
  type Pattern,
  type Project,
  type Song,
  type SongBody,
} from './lib/types';
export {
  type ChipDefinition,
  type InstrumentField,
  auditionChannelId,
  auditionChannelIndex,
  baseInstrument,
  chipDefinition,
  chipIds,
  chipLabel,
  instrumentForChannel,
  kindAllowedOnChannel,
} from './lib/chips';
export {
  activeSongBody,
  blankSongBody,
  emptyCell,
  newProject,
  newSong,
  songForRender,
  withActiveSong,
} from './lib/song-factory';
export {
  INSTRUMENT_PRESETS,
  instrumentFromPreset,
  presetsForChip,
  type InstrumentPreset,
} from './lib/presets';
export {
  addInstrument,
  addInstrumentFromPreset,
  addPattern,
  addRandomPattern,
  addSnipInstrument,
  addSong,
  armInstrument,
  armedInstrument,
  changeInstrumentKind,
  clearPattern,
  confirmationAccepted,
  deleteInstrument,
  duplicateBaseName,
  duplicatePattern,
  followPlaybackOrder,
  formatNote,
  loadProject,
  loadSong,
  markClean,
  newProjectForChip,
  newSession,
  nextBlankPatternName,
  nextDuplicatePatternName,
  noteFromKey,
  patternDisplayName,
  removeOrderEntry,
  removeSong,
  renameInstrument,
  renamePattern,
  reorderOrder,
  replaceWithRandom,
  selectOrder,
  selectSong,
  setChip,
  setEffect,
  setCellInstrument,
  findInstrumentIdByNumberLabel,
  setName,
  setOctave,
  setSongName,
  setTempo,
  updateInstrument,
  type SessionState,
  advanceColumn,
  clearCell,
  enterCut,
  enterNote,
  moveCursor,
  redo,
  setVolume,
  undo,
} from './lib/session';
export { ensureChannelInstruments, fillPatternRandom, randomProject, randomSong } from './lib/random-song';
