/**
 * Framework-free song model. Angular, the engines, and the file writers
 * all import this barrel and nothing underneath it.
 */
export {
  LEGACY_PROJECT_VERSION,
  PATTERN_ROWS,
  PROJECT_VERSION,
  PROJECT_VERSION_V2,
  PROJECT_VERSION_V3,
  PROJECT_VERSION_V4,
  PROJECT_VERSION_V5,
  EFFECT_CMDS,
  SHARED_EFFECT_CMDS,
  LSDJ_EFFECT_CMDS,
  effectCmdsForChip,
  effectValueMax,
  formatEffect,
  isEffectCmdForChip,
  remapLegacySharedEffectForGameboy,
  type Cell,
  type CellEffect,
  type ChipId,
  type ColumnId,
  type Cursor,
  type CustomInstrumentPreset,
  type EffectCmd,
  type FmOperator,
  type FmPatch,
  type Instrument,
  type InstrumentKind,
  type InstrumentPatch,
  type Pattern,
  type PresetRole,
  type Project,
  type Song,
  type SongBody,
} from './lib/types';
export {
  LSDJ_CHAIN_LENGTH,
  LSDJ_CHANNELS,
  LSDJ_CHANNEL_LABELS,
  LSDJ_GROOVE_COUNT,
  LSDJ_GROOVE_LENGTH,
  LSDJ_MAX_CHAINS,
  LSDJ_MAX_PHRASES,
  LSDJ_PHRASE_LENGTH,
  LSDJ_SEQUENCE_ROWS,
  LSDJ_TABLE_COUNT,
  LSDJ_TABLE_LENGTH,
  addHierarchyTable,
  allocateChainAt,
  allocatePhraseAt,
  blankChainSteps,
  blankLsdjChain,
  blankLsdjPhrase,
  blankLsdjTable,
  blankTableStep,
  canExpandFlatToHierarchy,
  chainAt,
  channelFlatSlots,
  clearPhrase,
  defaultGrooves,
  derivedOrderEntries,
  emptyPhraseSteps,
  emptySequence,
  expandFlatToHierarchy,
  findChain,
  findPhrase,
  findTable,
  flatCellTarget,
  focusedChainIndex,
  focusedPhraseIndex,
  hasLsdjHierarchy,
  isLsdjMode,
  lsdjHex,
  nextFreeChainIndex,
  nextFreePhraseIndex,
  nextFreeTableIndex,
  padChainSteps,
  padTableSteps,
  parseLsdjHex,
  phraseUseCounts,
  reexpandHierarchyFromFlat,
  setChainStep,
  setHierarchyFocus,
  setLsdjEnabled,
  setSequenceCell,
  signedTransposeByte,
  songRowCount,
  syncFlatProjection,
  toTransposeByte,
  updateHierarchyGroove,
  updateHierarchyTable,
  writeFlatCell,
  writePhraseStep,
  type DerivedOrderEntry,
  type LsdjChain,
  type LsdjChainStep,
  type LsdjFlatSlot,
  type LsdjFocus,
  type LsdjHierarchy,
  type LsdjPhrase,
  type LsdjTable,
  type LsdjTableStep,
} from './lib/lsdj-hierarchy';
export {
  effectColumnHint,
  effectHelp,
  effectReferenceForChip,
  type EffectHelp,
} from './lib/effects';
export {
  type ChipChannel,
  type ChipDefinition,
  type InstrumentField,
  type InstrumentFieldKey,
  auditionChannelId,
  auditionChannelIndex,
  baseInstrument,
  channelIsPlaceholder,
  chipDefinition,
  chipIds,
  chipLabel,
  instrumentForChannel,
  isChipId,
  isFmChip,
  kindAllowedOnChannel,
} from './lib/chips';
export {
  FM_ALGORITHMS,
  FM_ALGORITHM_OPTIONS,
  FM_OPERATOR_COUNT,
  FM_OPERATOR_FIELDS,
  defaultFmPatch,
  fmAlgorithmRouting,
  fmFieldValue,
  isFmPatchFieldKey,
  mergeFmPatch,
  patchFmField,
  patchFmOperator,
  type FmAlgorithmRouting,
  type FmOperatorFieldSpec,
  type FmPatchFieldKey,
} from './lib/fm';
export {
  activeSongBody,
  blankSongBody,
  emptyCell,
  newProject,
  newSong,
  songForRender,
  withActiveSong,
} from './lib/song-factory';
export {
  INSTRUMENT_PRESETS,
  defaultRoleForKind,
  groupPresetsForMenu,
  instrumentFromPreset,
  instrumentToPresetPatch,
  kindLabel as presetKindLabel,
  presetsForChip,
  roleLabel,
  type InstrumentPreset,
  type PresetKindGroup,
  type PresetMenuEntry,
  type PresetRoleGroup,
} from './lib/presets';
export {
  addInstrument,
  addInstrumentFromCustomPreset,
  addInstrumentFromPreset,
  addChainAt,
  addPattern,
  addPhraseAt,
  addRandomPattern,
  addSnipInstrument,
  addSong,
  addTable,
  armInstrument,
  armedInstrument,
  changeInstrumentKind,
  clearPattern,
  confirmationAccepted,
  deleteInstrument,
  duplicateBaseName,
  duplicatePattern,
  disableLsdjMode,
  enableLsdjMode,
  followPlaybackOrder,
  formatNote,
  clearLsdjOverlay,
  focusHierarchy,
  loadProject,
  lsdjModeAvailability,
  loadSong,
  markClean,
  newProjectForChip,
  newSession,
  setLsdjOverlay,
  nextBlankPatternName,
  nextDuplicatePatternName,
  noteFromKey,
  patternDisplayName,
  refreshLsdjProjection,
  removeOrderEntry,
  removeSong,
  renameInstrument,
  renamePattern,
  reorderOrder,
  removeCustomPreset,
  replaceWithRandom,
  importCustomPreset,
  saveCustomPreset,
  selectChainStep,
  selectOrder,
  selectSong,
  selectSongCell,
  setChip,
  setEffect,
  setCellInstrument,
  findInstrumentIdByNumberLabel,
  setName,
  setOctave,
  setSongName,
  setTempo,
  toggleLsdjMode,
  updateInstrument,
  writeChainStep,
  writeGroove,
  writeSongCell,
  writeTable,
  type LsdjImportMap,
  type LsdjPhraseRef,
  type SessionState,
  advanceColumn,
  clearCell,
  enterCut,
  enterNote,
  moveCursor,
  redo,
  setVolume,
  undo,
} from './lib/session';
export { ensureChannelInstruments, fillPatternRandom, randomProject, randomSong } from './lib/random-song';
